# Generated by Django 3.1.4 on 2020-12-25 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=10)),
                ('control_type', models.CharField(max_length=20)),
                ('control_name', models.TextField()),
                ('control_set_version_number', models.CharField(max_length=20)),
                ('authorization_package_name', models.TextField()),
                ('allocation_status', models.CharField(max_length=60)),
                ('overall_update_date', models.DateTimeField(blank=True, null=True)),
                ('overall_control_status', models.CharField(max_length=60)),
                ('assessment_status', models.CharField(max_length=60)),
                ('tracking_id', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ArsBaseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ars_baseline', models.CharField(max_length=10)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='cmsparser.control')),
            ],
        ),
    ]
